### ISSUE TITLE
Malformed URI throws Null Reference Exception

### ISSUE THREAD

**Issue by aamburn** [petrsnd/OtpCore#22]
This throws a null reference exception: 

`
var uri = "otpauth://totp/Test?&issuer=Test";
var totp = OtpCoreTotp.GetAuthenticator(uri);
`

Stacktrace: 

Object reference not set to an instance of an object.
   at Petrsnd.OtpCore.OtpAuthUri..ctor(Uri uri) in ..\OtpCore\OtpCore\OtpAuthUri.cs:line 104
   at Petrsnd.OtpCore.Totp.GetAuthenticator(Uri uri) in ..\OtpCore\OtpCore\Totp.cs:line 62
   at Petrsnd.OtpCore.Totp.GetAuthenticator(String uriString) in ..\OtpCore\OtpCore\Totp.cs:line 57

**Comment by petrsnd** [comment]
Fixed by #23
